## Sample Component kind (Namespaced)
apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: reading-list-service
  namespace: default-org
  annotations:
    openchoreo.dev/display-name: Reading List Service
    openchoreo.dev/description: Reading List Server Application
  labels:
    openchoreo.dev/organization: default-org
    openchoreo.dev/project: default-project
    openchoreo.dev/name: reading-list-service
spec:
  type: Service
  source:
    containerRegistry:
      imageName: ghcr.io/openchoreo/samples/reading-list-server
---
## Sample DeploymentTrack kind (Namespaced)
apiVersion: openchoreo.dev/v1alpha1
kind: DeploymentTrack
metadata:
  name: reading-list-service-main
  namespace: default-org
  annotations:
    openchoreo.dev/display-name: Main deployment track
    openchoreo.dev/description: The main deployment track for the reading-list-service component
  labels:
    openchoreo.dev/organization: default-org
    openchoreo.dev/project: default-project
    openchoreo.dev/component: reading-list-service
    openchoreo.dev/name: main
spec: {}
---
## Sample Deployable Artifact kind (Namespaced)
apiVersion: openchoreo.dev/v1alpha1
kind: DeployableArtifact
metadata:
  name: reading-list-service
  namespace: default-org
  annotations:
    openchoreo.dev/description: Deployable Artifact for reading list server
    openchoreo.dev/display-name: reading-list-service
  labels:
    openchoreo.dev/organization: default-org
    openchoreo.dev/project: default-project
    openchoreo.dev/component: reading-list-service
    openchoreo.dev/deployment-track: main
    openchoreo.dev/name: reading-list-service
spec:
  configuration:
    endpointTemplates:
      - metadata:
          name: service-port
        spec:
          networkVisibilities:
            public:
              enable: false
            organization:
              enable: true
          service:
            basePath: /
            port: 8080
          type: HTTP
  targetArtifact:
    fromImageRef:
      tag: latest
---
## Sample Deployment kind (Namespaced)
apiVersion: openchoreo.dev/v1alpha1
kind: Deployment
metadata:
  name: reading-list-service-deployment
  namespace: default-org
  annotations:
    openchoreo.dev/display-name: reading-list-service deployment
  labels:
    openchoreo.dev/organization: default-org
    openchoreo.dev/project: default-project
    openchoreo.dev/environment: development
    openchoreo.dev/component: reading-list-service
    openchoreo.dev/deployment-track: main
    openchoreo.dev/name: reading-list-service-deployment
spec:
  deploymentArtifactRef: reading-list-service
