## Sample Organization kind (Cluster-scoped)
apiVersion: openchoreo.dev/v1alpha1
kind: Organization
metadata:
  name: acme
  annotations:
    openchoreo.dev/display-name: ACME Organization
    openchoreo.dev/description: Choreo Organization for ACME
  labels:
    openchoreo.dev/name: acme
spec: {}
---

## Sample DataPlane kind (Namespaced) - add cluster credentials before applying
apiVersion: openchoreo.dev/v1alpha1
kind: DataPlane
metadata:
  name: dp-local
  namespace: acme
  annotations:
    openchoreo.dev/display-name: Local Data Plane
    openchoreo.dev/description: Data plane in Kind cluster
  labels:
    openchoreo.dev/build-plane: "true"
    openchoreo.dev/name: dp-local
    openchoreo.dev/organization: acme
spec:
  gateway:
    organizationVirtualHost: choreoapis.internal
    publicVirtualHost: choreoapis.localhost
  kubernetesCluster:
    credentials:
      apiServerURL: https://127.0.0.1:63321
      caCert: xxx
      clientCert: xxx
      clientKey: xxx
    name: kind-choreo
  registry:
    unauthenticated:
      - registry.choreo-system:5000
---

## Sample DeploymentPipeline kind (Namespaced)
apiVersion: openchoreo.dev/v1alpha1
kind: DeploymentPipeline
metadata:
  name: pipeline-dev-stage-prod
  namespace: acme
  annotations:
    openchoreo.dev/display-name: Default Deployment Pipeline
    openchoreo.dev/description: Allows promoting from dev to production
  labels:
    openchoreo.dev/organization: acme
    openchoreo.dev/name: pipeline-dev-stage-prod
spec:
  promotionPaths:
    - sourceEnvironmentRef: development
      targetEnvironmentRefs:
        - name: staging
          requiresApproval: false
        - name: production
          isManualApprovalRequired: true
    - sourceEnvironmentRef: staging
      targetEnvironmentRefs:
        - name: production
          requiresApproval: true
---

## Sample Environment kind (Namespaced)
apiVersion: openchoreo.dev/v1alpha1
kind: Environment
metadata:
  name: development
  namespace: acme
  annotations:
    openchoreo.dev/display-name: Development Environment
    openchoreo.dev/description: The environment where you can play around
  labels:
    openchoreo.dev/organization: acme
    openchoreo.dev/name: development
spec:
  dataPlaneRef: dp-local 
  isProduction: false
  gateway:
    dnsPrefix: local-dev
---

## Sample Project kind (Namespaced)
apiVersion: openchoreo.dev/v1alpha1
kind: Project
metadata:
  name: customer-portal
  namespace: acme
  annotations:
    openchoreo.dev/display-name: Customer Portal
    openchoreo.dev/description: This project contains types that are used by Acme customer portal
  labels:
    openchoreo.dev/organization: acme
    openchoreo.dev/name: customer-portal
spec:
  deploymentPipelineRef: pipeline-dev-stage-prod
