## Sample Component kind (Namespaced)
apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: reading-list-python-service
  namespace: default-org
  annotations:
    openchoreo.dev/display-name: Reading List Python Component
    openchoreo.dev/description: A simple REST API service for managing a reading list.
  labels:
    openchoreo.dev/organization: default-org
    openchoreo.dev/project: default-project
    openchoreo.dev/name: reading-list-python-service
spec:
  type: Service
  source:
    gitRepository:
      url: https://github.com/wso2/choreo-samples
      authentication:
        secretRef: choreo-bot-git-pat
---

## Sample DeploymentTrack kind (Namespaced)
apiVersion: openchoreo.dev/v1alpha1
kind: DeploymentTrack
metadata:
  name: reading-list-python-service-main
  namespace: default-org
  annotations:
    openchoreo.dev/display-name: Main Deployment Track
    openchoreo.dev/description: Deployment track for the Reading List Python service.
  labels:
    openchoreo.dev/organization: default-org
    openchoreo.dev/project: default-project
    openchoreo.dev/component: reading-list-python-service
    openchoreo.dev/name: reading-list-python-service-main
spec:
  buildTemplateSpec:
    branch: main
    path: /reading-books-list-service-python
    buildConfiguration:
      buildpack:
        name: Python
---

## Sample Build kind (Namespaced)
apiVersion: openchoreo.dev/v1alpha1
kind: Build
metadata:
  name: reading-list-python-service-build-01
  namespace: default-org
  annotations:
    openchoreo.dev/display-name: Default Build
    openchoreo.dev/description: Initial build configuration for the Reading List Python service.
  labels:
    openchoreo.dev/organization: default-org
    openchoreo.dev/project: default-project
    openchoreo.dev/component: reading-list-python-service
    openchoreo.dev/deployment-track: reading-list-python-service-main
    openchoreo.dev/name: reading-list-python-service-build-01
spec:
  branch: main
  path: /reading-books-list-service-python
  buildConfiguration:
    buildpack:
      name: Python
      version: 3.10.x
---

#### Sample Deployment kind (Namespaced)
apiVersion: openchoreo.dev/v1alpha1
kind: Deployment
metadata:
  name: reading-list-python-service-development-deployment-01
  namespace: default-org
  annotations:
    openchoreo.dev/display-name: Reading List Python Service Deployment
    openchoreo.dev/description: Initial deployment configuration for the Reading List Python service.
  labels:
    openchoreo.dev/organization: default-org
    openchoreo.dev/project: default-project
    openchoreo.dev/environment: development
    openchoreo.dev/component: reading-list-python-service
    openchoreo.dev/deployment-track: reading-list-python-service-main
    openchoreo.dev/name: reading-list-python-service-development-deployment-01
spec:
  deploymentArtifactRef: reading-list-python-service-build-01
