## Sample Component kind (Namespaced)
apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: patient-management-service
  namespace: default-org
  annotations:
    openchoreo.dev/display-name: Patient Management Ballerina Component
    openchoreo.dev/description: This component can send manage patients through its REST API
  labels:
    openchoreo.dev/organization: default-org
    openchoreo.dev/project: default-project
    openchoreo.dev/name: patient-management-service
spec:
  type: Service
  source:
    gitRepository:
      url: https://github.com/wso2/choreo-samples
      authentication:
        secretRef: choreo-bot-git-pat
---

## Sample DeploymentTrack kind (Namespaced)
apiVersion: openchoreo.dev/v1alpha1
kind: DeploymentTrack
metadata:
  name: patient-management-service-main
  namespace: default-org
  annotations:
    openchoreo.dev/display-name: Deployment Track
    openchoreo.dev/description: Main deployment track
  labels:
    openchoreo.dev/organization: default-org
    openchoreo.dev/project: default-project
    openchoreo.dev/component: patient-management-service
    openchoreo.dev/name: patient-management-service-main
spec:
  buildTemplateSpec:
    branch: main
    path: /patient-management-service
    buildConfiguration:
      buildpack:
        name: Ballerina
---

## Sample Build kind (Namespaced)
apiVersion: openchoreo.dev/v1alpha1
kind: Build
metadata:
  name: patient-management-service-build-01
  namespace: default-org
  annotations:
    openchoreo.dev/display-name: Default Build
    openchoreo.dev/description: Initial build configuration
  labels:
    openchoreo.dev/organization: default-org
    openchoreo.dev/project: default-project
    openchoreo.dev/component: patient-management-service
    openchoreo.dev/deployment-track: patient-management-service-main
    openchoreo.dev/name: patient-management-service-build-01
spec:
  branch: main
  path: /patient-management-service
  buildConfiguration:
    buildpack:
      name: Ballerina
      version: 2201.10.4
---

#### Sample Deployment kind (Namespaced)
apiVersion: openchoreo.dev/v1alpha1
kind: Deployment
metadata:
  name: patient-management-service-development-deployment-01
  namespace: default-org
  annotations:
    openchoreo.dev/display-name: Deployment of Patient Management App
    openchoreo.dev/description: Initial deployment configuration
  labels:
    openchoreo.dev/organization: default-org
    openchoreo.dev/project: default-project
    openchoreo.dev/environment: development
    openchoreo.dev/component: patient-management-service
    openchoreo.dev/deployment-track: patient-management-service-main
    openchoreo.dev/name: patient-management-service-development-deployment-01
spec:
  deploymentArtifactRef: patient-management-service-build-01
