## Sample Environment kind (Namespaced)
apiVersion: openchoreo.dev/v1alpha1
kind: Environment
metadata:
  name: development
  namespace: acme
  annotations:
    openchoreo.dev/display-name: Development Environment
    openchoreo.dev/description: The development environment for rapid integration and testing.
  labels:
    openchoreo.dev/organization: acme
    openchoreo.dev/name: development
spec:
  dataPlaneRef: us-east-1
  isProduction: false
  gateway:
    dnsPrefix: dev
