## Sample Environment kind (Namespaced)
apiVersion: openchoreo.dev/v1alpha1
kind: Environment
metadata:
  name: staging
  namespace: acme
  annotations:
    openchoreo.dev/display-name: Staging Environment
    openchoreo.dev/description: The staging environment for rapid integration and testing.
  labels:
    openchoreo.dev/organization: acme
    openchoreo.dev/name: staging
spec:
  dataPlaneRef: us-east-1
  isProduction: false
  gateway:
    dnsPrefix: stage
