## Sample DeploymentPipeline kind (Namespaced)
apiVersion: openchoreo.dev/v1alpha1
kind: DeploymentPipeline
metadata:
  name: pipeline-dev-stage-prod
  namespace: acme
  annotations:
    openchoreo.dev/display-name: Default Deployment Pipeline
    openchoreo.dev/description: Allows promoting from development, staging to production environments.
  labels:
    openchoreo.dev/organization: acme
    openchoreo.dev/name: pipeline-dev-stage-prod
spec:
  promotionPaths:
    - sourceEnvironmentRef: development
      targetEnvironmentRefs:
        - name: staging
          requiresApproval: false
        - name: production
          isManualApprovalRequired: true
    - sourceEnvironmentRef: staging
      targetEnvironmentRefs:
        - name: production
          requiresApproval: true
