## Sample Component kind (Namespaced)
apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: reading-list-service
  namespace: default-org
  annotations:
    openchoreo.dev/display-name: Reading List Service
    openchoreo.dev/description: A REST API to manage a reading list of books
  labels:
    openchoreo.dev/organization: default-org
    openchoreo.dev/project: default-project
    openchoreo.dev/name: reading-list-service
spec:
  type: Service
  source:
    gitRepository:
      url: https://github.com/wso2/choreo-samples
---

## Sample DeploymentTrack kind (Namespaced)
apiVersion: openchoreo.dev/v1alpha1
kind: DeploymentTrack
metadata:
  name: reading-list-service-main
  namespace: default-org
  annotations:
    openchoreo.dev/display-name: Main deployment track
    openchoreo.dev/description: The main deployment track for the reading-list-service component
  labels:
    openchoreo.dev/organization: default-org
    openchoreo.dev/project: default-project
    openchoreo.dev/component: reading-list-service
    openchoreo.dev/name: reading-list-service-main
spec:
  buildTemplateSpec:
    branch: main
    path: /go-reading-list-rest-api
    buildConfiguration:
      buildpack:
        name: Go
        version: 1.x
---

## Sample Build kind (Namespaced)
apiVersion: openchoreo.dev/v1alpha1
kind: Build
metadata:
  name: reading-list-service-build-01
  namespace: default-org
  annotations:
    openchoreo.dev/display-name: Build for Reading List Service
    openchoreo.dev/description: Build triggered for the Reading List Service
  labels:
    openchoreo.dev/organization: default-org
    openchoreo.dev/project: default-project
    openchoreo.dev/component: reading-list-service
    openchoreo.dev/deployment-track: reading-list-service-main
    openchoreo.dev/name: reading-list-service-build-01
spec:
  branch: main
  path: /go-reading-list-rest-api
  buildConfiguration:
    buildpack:
      name: Go
      version: 1.x
---

## Sample Deployment kind (Namespaced)
apiVersion: openchoreo.dev/v1alpha1
kind: Deployment
metadata:
  name: reading-list-service-development-deployment-01
  namespace: default-org
  annotations:
    openchoreo.dev/display-name: Reading List Service Deployment
    openchoreo.dev/description: Deployment for the Reading List Service
  labels:
    openchoreo.dev/organization: default-org
    openchoreo.dev/project: default-project
    openchoreo.dev/environment: development
    openchoreo.dev/component: reading-list-service
    openchoreo.dev/deployment-track: reading-list-service-main
    openchoreo.dev/name: reading-list-service-development-deployment-01
spec:
  deploymentArtifactRef: reading-list-service-build-01
