# permissions for end users to edit workloadclasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: choreo
    app.kubernetes.io/managed-by: kustomize
  name: workloadclass-editor-role
rules:
- apiGroups:
  - core.choreo.dev
  resources:
  - workloadclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.choreo.dev
  resources:
  - workloadclasses/status
  verbs:
  - get
