apiVersion: core.choreo.dev/v1
kind: Environment
metadata:
  annotations:
    core.choreo.dev/description: Production
    core.choreo.dev/display-name: Production
  labels:
    core.choreo.dev/name: production
    core.choreo.dev/organization: default-org
  name: production
  namespace: default
spec:
  dataPlaneRef: default
  gateway:
    dnsPrefix: prod
    security:
      remoteJwks:
        uri: ""