## Sample DeploymentPipeline kind (Namespaced)
apiVersion: openchoreo.dev/v1alpha1
kind: DeploymentPipeline
metadata:
  name: default-pipeline
  namespace: default-org
  annotations:
    openchoreo.dev/display-name: Default Deployment Pipeline
    openchoreo.dev/description: Allows promoting from development, staging to production environments.
  labels:
    openchoreo.dev/organization: default-org
    openchoreo.dev/name: default-pipeline
spec:
  promotionPaths:
    - sourceEnvironmentRef: development
      targetEnvironmentRefs:
      - name: test
        requiresApproval: false
    - sourceEnvironmentRef: test
      targetEnvironmentRefs:
        - name: staging
          requiresApproval: false
        - name: production
          isManualApprovalRequired: true
    - sourceEnvironmentRef: staging
      targetEnvironmentRefs:
        - name: production
          requiresApproval: true
