## Sample Environment kind (Namespaced)
apiVersion: openchoreo.dev/v1alpha1
kind: Environment
metadata:
  name: test
  namespace: default-org
  annotations:
    openchoreo.dev/display-name: Test Environment
    openchoreo.dev/description: The test environment for testing.
  labels:
    openchoreo.dev/organization: default-org
    openchoreo.dev/name: test
spec:
  dataPlaneRef: us-east-1
  isProduction: false
  gateway:
    dnsPrefix: test
