## Sample Component kind (Namespaced)
apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: react-starter
  namespace: default-org
  annotations:
    openchoreo.dev/display-name: React Starter
    openchoreo.dev/description: Basic Starter project
  labels:
    openchoreo.dev/organization: default-org
    openchoreo.dev/project: default-project
    openchoreo.dev/name: react-starter
spec:
  type: WebApplication
  source:
    gitRepository:
      url: https://github.com/docker/awesome-compose
      authentication:
        secretRef: choreo-bot-git-pat
---
## Sample DeploymentTrack kind (Namespaced)
apiVersion: openchoreo.dev/v1alpha1
kind: DeploymentTrack
metadata:
  name: react-starter-main
  namespace: default-org
  annotations:
    openchoreo.dev/display-name: Main deployment track
    openchoreo.dev/description: The main deployment track for the react-starter component
  labels:
    openchoreo.dev/organization: default-org
    openchoreo.dev/project: default-project
    openchoreo.dev/component: react-starter
    openchoreo.dev/name: main
spec:
  buildTemplateSpec:
    branch: master
    path: /react-nginx
    buildConfiguration:
      docker:
        context: /react-nginx
        dockerfilePath: /react-nginx/Dockerfile
---
## Sample Build kind (Namespaced)
apiVersion: openchoreo.dev/v1alpha1
kind: Build
metadata:
  name: react-starter-build-01
  namespace: default-org
  annotations:
    openchoreo.dev/display-name: Build for react-starter
    openchoreo.dev/description: Build 1 triggered for react-starter
  labels:
    openchoreo.dev/organization: default-org
    openchoreo.dev/project: default-project
    openchoreo.dev/component: react-starter
    openchoreo.dev/deployment-track: main
    openchoreo.dev/name: react-starter-build
spec:
  branch: master
  path: /react-nginx
  buildConfiguration:
    docker:
      context: /react-nginx
      dockerfilePath: /react-nginx/Dockerfile
---
## Sample Deployment kind (Namespaced)
apiVersion: openchoreo.dev/v1alpha1
kind: Deployment
metadata:
  name: react-starter-deployment
  namespace: default-org
  annotations:
    openchoreo.dev/display-name: react-starter deployment
  labels:
    openchoreo.dev/organization: default-org
    openchoreo.dev/project: default-project
    openchoreo.dev/environment: development
    openchoreo.dev/component: react-starter
    openchoreo.dev/deployment-track: main
    openchoreo.dev/name: react-starter-deployment
spec:
  deploymentArtifactRef: react-starter-build-01
