## Sample Component kind (Namespaced)
apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: time-logger
  namespace: default-org
  annotations:
    openchoreo.dev/display-name: Time Logger Component
    openchoreo.dev/description: This component logs the time periodically
  labels:
    openchoreo.dev/organization: default-org
    openchoreo.dev/project: default-project
    openchoreo.dev/name: time-logger
spec:
  type: ScheduledTask
  source:
    gitRepository:
      url: https://github.com/wso2/choreo-samples
      authentication:
        secretRef: choreo-bot-git-pat
---

## Sample DeploymentTrack kind (Namespaced)
apiVersion: openchoreo.dev/v1alpha1
kind: DeploymentTrack
metadata:
  name: time-logger-main
  namespace: default-org
  annotations:
    openchoreo.dev/display-name: Deployment Track
    openchoreo.dev/description: Main deployment track
  labels:
    openchoreo.dev/organization: default-org
    openchoreo.dev/project: default-project
    openchoreo.dev/component: time-logger
    openchoreo.dev/name: time-logger-main
spec:
  buildTemplateSpec:
    branch: main
    path: /docker-time-logger-schedule
    buildConfiguration:
      buildpack:
        name: Go
---

## Sample Build kind (Namespaced)
apiVersion: openchoreo.dev/v1alpha1
kind: Build
metadata:
  name: time-logger-build-01
  namespace: default-org
  annotations:
    openchoreo.dev/display-name: Default Build
    openchoreo.dev/description: Initial build configuration
  labels:
    openchoreo.dev/organization: default-org
    openchoreo.dev/project: default-project
    openchoreo.dev/component: time-logger
    openchoreo.dev/deployment-track: time-logger-main
    openchoreo.dev/name: time-logger-build-01
spec:
  branch: main
  path: /docker-time-logger-schedule
  buildConfiguration:
    buildpack:
      name: Go
      version: 1.x
---

#### Sample Deployment kind (Namespaced)
apiVersion: openchoreo.dev/v1alpha1
kind: Deployment
metadata:
  name: time-logger-development-deployment-01
  namespace: default-org
  annotations:
    openchoreo.dev/display-name: Deployment of Time Logger
    openchoreo.dev/description: Initial deployment configuration
  labels:
    openchoreo.dev/organization: default-org
    openchoreo.dev/project: default-project
    openchoreo.dev/environment: development
    openchoreo.dev/component: time-logger
    openchoreo.dev/deployment-track: time-logger-main
    openchoreo.dev/name: time-logger-development-deployment
spec:
  deploymentArtifactRef: time-logger-build-01
